"""Change enum to string

Revision ID: 6184062f7e38
Revises: 6ecea9323ccb
Create Date: 2020-05-15 20:40:40.528210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6184062f7e38'
down_revision = '6ecea9323ccb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_profile") as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('ADMIN', 'MEMBER', name='userrole'),
               type_=sa.String(length=128))

    with op.batch_alter_table("question_set") as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.Enum('PHOTO', 'TEXT', name='category'),
               type_=sa.String(length=128))

    with op.batch_alter_table("promotion_action") as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('BASIC', 'PREMIUM', name='promotiontype'),
               type_=sa.String(length=128))

    with op.batch_alter_table("question_set_report") as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('INAPPROPRIATE_CONTENT', name='reporttype'),
               type_=sa.String(length=128))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_profile") as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=128),
               type_=sa.Enum('ADMIN', 'MEMBER', name='userrole'))

    with op.batch_alter_table("question_set") as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.String(length=128),
               type_=sa.Enum('PHOTO', 'TEXT', name='category'))

    with op.batch_alter_table("promotion_action") as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.String(length=128),
               type_=sa.Enum('BASIC', 'PREMIUM', name='promotiontype'))

    with op.batch_alter_table("question_set_report") as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.String(length=128),
               type_=sa.Enum('INAPPROPRIATE_CONTENT', name='reporttype'))
    # ### end Alembic commands ###
