"""added question set open date

Revision ID: 68c00b425d77
Revises: aeb9553220d8
Create Date: 2020-05-18 12:25:31.634932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68c00b425d77'
down_revision = 'aeb9553220d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_set', sa.Column('open_date', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_set', 'open_date')
    # ### end Alembic commands ###
