"""question set tags

Revision ID: 77d38d83ec29
Revises: 6184062f7e38
Create Date: 2020-05-18 11:41:26.704047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77d38d83ec29'
down_revision = '6184062f7e38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_set_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_set_to_tag',
    sa.Column('question_set_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('difficulty_level', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['question_set_id'], ['question_set.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['question_set_tag.id'], ),
    sa.PrimaryKeyConstraint('question_set_id', 'tag_id')
    )
    op.alter_column('question_set_report', 'type',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.add_column('user_account', sa.Column('user_state', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account', 'user_state')
    op.alter_column('question_set_report', 'type',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.drop_table('question_set_to_tag')
    op.drop_table('question_set_tag')
    # ### end Alembic commands ###
