"""empty message

Revision ID: 791d3ea2ece9
Revises: 7ed803481c92
Create Date: 2020-05-26 00:46:26.880705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '791d3ea2ece9'
down_revision = '7ed803481c92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_set', sa.Column('to_update', sa.Boolean(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_set', 'to_update')
    # ### end Alembic commands ###
