"""Removed question set category

Revision ID: 7ed803481c92
Revises: 68c00b425d77
Create Date: 2020-05-18 15:46:25.646051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ed803481c92'
down_revision = '68c00b425d77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_set', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_set', sa.Column('category', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
